# Generated by Django 6.0.3 on 2026-04-28 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_chatsession_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='active_source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
